// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/controller/interfaces.go -destination=test/mocks/mock_cluster_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockClusterClientGetter is a mock of ClusterClientGetter interface.
type MockClusterClientGetter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientGetterMockRecorder
	isgomock struct{}
}

// MockClusterClientGetterMockRecorder is the mock recorder for MockClusterClientGetter.
type MockClusterClientGetterMockRecorder struct {
	mock *MockClusterClientGetter
}

// NewMockClusterClientGetter creates a new mock instance.
func NewMockClusterClientGetter(ctrl *gomock.Controller) *MockClusterClientGetter {
	mock := &MockClusterClientGetter{ctrl: ctrl}
	mock.recorder = &MockClusterClientGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClientGetter) EXPECT() *MockClusterClientGetterMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockClusterClientGetter) GetClient(kubeconfigSecret *v1.Secret) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", kubeconfigSecret)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClusterClientGetterMockRecorder) GetClient(kubeconfigSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClusterClientGetter)(nil).GetClient), kubeconfigSecret)
}
